/**********************************************************************************/
/*************************** Name : Omar Tarek ************************************/
/*************************** Date : 18/3/2024  ************************************/
/*************************** SWC : DIO         ************************************/
/*************************** Version : 1.0     ************************************/
/**********************************************************************************/

#ifndef DIO_CONFIGURATION_H
#define DIO_CONFIGURATION_H

/************************************** Initial Directions for all PINs ***************************************/
/* Options : DIO_u8_INIT_OUTPUT
             DIO_u8_INIT_INPUT*/

/* PORTA */
#define DIO_u8_PA0_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PA1_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PA2_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PA3_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PA4_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PA5_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PA6_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PA7_INIT_DIRECTION DIO_u8_INIT_INPUT
/* PORTB */
#define DIO_u8_PB0_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PB1_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PB2_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PB3_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PB4_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PB5_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PB6_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PB7_INIT_DIRECTION DIO_u8_INIT_INPUT
/* PORTC */
#define DIO_u8_PC0_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PC1_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PC2_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PC3_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PC4_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PC5_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PC6_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PC7_INIT_DIRECTION DIO_u8_INIT_INPUT
/* PORTD */
#define DIO_u8_PD0_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PD1_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PD2_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PD3_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PD4_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PD5_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PD6_INIT_DIRECTION DIO_u8_INIT_INPUT
#define DIO_u8_PD7_INIT_DIRECTION DIO_u8_INIT_INPUT
/************************************************************************************************************/
/************************************** Initial values for all PINs ***************************************/
/* Options : DIO_u8_OUTPUT_LOW
             DIO_u8_OUTPUT_LOW
             DIO_u8_INPUT_FLOATING
             DIO_u8_INPUT_PULLUP */

#define DIO_u8_PA0_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PA1_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PA2_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PA3_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PA4_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PA5_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PA6_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PA7_INIT_VALUE DIO_u8_INPUT_FLOATING
/* PORTB */
#define DIO_u8_PB0_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PB1_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PB2_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PB3_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PB4_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PB5_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PB6_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PB7_INIT_VALUE DIO_u8_INPUT_FLOATING
/* PORTC */
#define DIO_u8_PC0_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PC1_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PC2_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PC3_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PC4_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PC5_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PC6_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PC7_INIT_VALUE DIO_u8_INPUT_FLOATING
/* PORTD */
#define DIO_u8_PD0_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PD1_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PD2_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PD3_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PD4_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PD5_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PD6_INIT_VALUE DIO_u8_INPUT_FLOATING
#define DIO_u8_PD7_INIT_VALUE DIO_u8_INPUT_FLOATING

#endif